version: '2'

services:
 web1:
  image: amanu/php56-apache
  volumes:
   - ./bendahara:/var/www/html/
  ports:
   - "8004:80"
  links:
   - "db1:sql"

 db1:
  build: .
  container_name: sql
  ports:
   - "3006:3306"
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_DATABASE: HMJ_TI_Bebdahara
   MYSQL_USER: root
   MYSQL_PASSWORD: test
   MYSQL_ROOT_PASSWORD: test

volumes:
 db_data:
